### ISSUE TITLE
Add Online IDE Feature

### ISSUE THREAD

**Issue by Traveller08** [Traveller08/wecode#17]
**Description:**

We would like to introduce a new feature to wecode—a built-in online integrated development environment (IDE). This feature will enable users to write, compile, and run code directly within the platform.

**Feature Requirements:**
- Integration of a code editor with syntax highlighting for multiple programming languages.
- Ability to compile and execute code in real-time.
- Support for input and output panels.
- User-friendly interface with features like code auto-completion and error highlighting.
- Saving and loading code projects.
- Integration with existing user accounts for a seamless experience.

**Suggested Approach:**
- Research and select an appropriate code editor or IDE platform for integration. (Links for your reference [Link1](https://www.geeksforgeeks.org/embedding-an-online-compiler-into-a-website/) [Link2](https://www.freecodecamp.org/news/how-to-build-react-based-code-editor/))
- Plan the user interface and user experience for the IDE.
- Implement the necessary backend and frontend components for code execution.
- Ensure security measures to protect user data and code.

**Additional Information:**
- Any specific programming languages or technologies to prioritize.
- Compatibility considerations with the existing platform.
- Screenshots or design mockups (if available).

**Acceptance Criteria:**
- The online IDE feature should be fully functional and integrated into the wecode platform.

**Comment by JulianToppo** [comment]
Could i please assigned to work on this issue?

**Comment by Traveller08** [comment]
Hey @JulianToppo , we're already using react-hot-toast for toasts on the website. Therefore, we should use react-hot-toast instead of react-toastify." Don't worry about the setup because it is already done, You can import toast from "react-hot-toast" and can use the provided themes for diplaying the toasts. For more info refer to [link](https://react-hot-toast.com/docs/toast).
