### ISSUE TITLE
Add 404 - NotFound page

### ISSUE THREAD

**Issue by MohammedAmmarGit** [Traveller08/wecode#20]
![bug](https://github.com/Traveller08/wecode/assets/97389335/070bb2ad-392c-4723-afc6-0929d436b846)

- If we try to access through invalid URL, It shows black as shown in Image.
- To fix this, need to add NotFound page

**Comment by MohammedAmmarGit** [comment]
Please assigned this issue to

**Comment by Prathamdas3** [comment]
Can I work on this?

**Comment by Traveller08** [comment]
@MohammedAmmarGit  I have assigned you the issue, you can work on it.
