### ISSUE TITLE
Display Contest Problems with Indices and User Status Colors

### ISSUE THREAD

**Issue by Traveller08** [Traveller08/wecode#5]
**Description:**

Currently, when viewing a contest, problems aren't, and there's no visual indication of a user's status (solved, attempted) for each problem. We would like to enhance the user experience by displaying problems with their indices and using color codes to indicate the user's status.

**Desired Feature:**
- Go to practice -> contests section -> select any contest from the dropdown.
- Display the contest's problems with their respective indices (A, B, C, etc.) in front of the contest names.
- Implement color coding for each problem based on the user's status:
  - Green: Problem solved by the user.
  - Red: Problem attempted but not solved.
  - Default (e.g., black): Problem not attempted by the user.

**Example:**
- [A] Problem 1 (Green)
- [B] Problem 2 (Red)
- [C] Problem 3

**Suggested Solution:**
- Modify the UI to include problem indices.
- Implement conditional styling based on user status (CSS or frontend logic).
- Retrieve user data related to the question using the Codeforces API.  

**Additional Information:**
<img width="943" alt="Screenshot 2023-10-01 101603" src="https://github.com/Traveller08/wecode/assets/75868415/fcaf123c-719a-46e4-a12b-e9ace65ba155">
The problem indices should be after the contest name.

**Acceptance Criteria:**
- When viewing a contest, problems should be listed with their indices and colors reflecting the user's status as described above.

**Comment by Bidexdablitz** [comment]
Please i would like to work on this issue😀

**Comment by Traveller08** [comment]
Hi @Bidexdablitz I have assigned you the issue.

**Comment by Bidexdablitz** [comment]
Hi @Traveller08, please can you review my PR <3

**Comment by Traveller08** [comment]
I have merged it. Thanks for your contribution.
