### ISSUE TITLE
 Ensure Consistent Alignment of Buttons After Contest Name

### ISSUE THREAD

**Issue by Traveller08** [Traveller08/wecode#6]
**Description:**

Currently, the buttons that appear after the contest name do not start at the same place in all rows. This inconsistency in alignment can affect the visual appeal and usability of the interface.

**Steps to Reproduce:**
1. Go to Practice -> contest section.
2. Observe the alignment of buttons after the contest names in different rows.

**Expected Behavior:**
The buttons following the contest name should consistently start at the same horizontal position in all rows.

**Actual Behavior:**
The alignment of these buttons varies between rows.

**Suggested Solution:**
- Review and adjust the CSS styles to ensure consistent button alignment.
- Implement responsive design practices to maintain alignment across different screen sizes.

**Additional Information:**
<img width="943" alt="Screenshot 2023-10-01 101603" src="https://github.com/Traveller08/wecode/assets/75868415/6529260b-6903-4cad-a48c-c39df4d48398">

**Acceptance Criteria:**
- After the improvement, the buttons following the contest name should consistently align at the same horizontal position in all rows.

**Comment by shahank42** [comment]
Hi!
I am interested in working on this issue. Could I be assigned to it?

**Comment by Traveller08** [comment]
Hi @shahank42 
I have assigned you the issue, you can work on it.

**Comment by Tombstoner** [comment]
can you review my pull request ??

**Comment by Traveller08** [comment]
Your pull request has been successfully merged into the project. Thank you @shahank42  for your valuable contribution!
