### ISSUE TITLE
Ensure Consistent Card Size for Problems

### ISSUE THREAD

**Issue by Traveller08** [Traveller08/wecode#8]
**Description:**

Currently, there is inconsistency in the card sizes for problems, which affects the overall layout and visual presentation of the content.

**Steps to Reproduce:**
1. Go to the practice -> problems section.
2. Observe the card sizes for different problems.

**Expected Behavior:**
The card size for all problems should be consistent and uniform.

**Actual Behavior:**
The card sizes vary between problems.

**Suggested Solution:**
- Review and update CSS styles to ensure that all problem cards have the same dimensions.
- Implement responsive design practices to maintain card size consistency across different screen sizes.

**Additional Information:**
<img width="960" alt="Screenshot 2023-10-01 103209" src="https://github.com/Traveller08/wecode/assets/75868415/c8a8c636-0acb-41bf-a446-c93f99852943">

**Acceptance Criteria:**
- After the improvement, the card size for all problems should be the same and consistent throughout the problems section.

**Comment by Sky-De** [comment]
@Traveller08 hi there, i would like to fix this for you, please assign this to me
Thanks

**Comment by Traveller08** [comment]
Hi @Sky-De, you can work on this issue.

**Comment by Tombstoner** [comment]
I have added a commit please review that.

**Comment by Traveller08** [comment]
> I have added a commit please review that.

@Tombstoner , if you delete all the code in the file and then add it again, it becomes difficult to track changes in the files. Instead, please open another pull request in which you make changes to the existing code without deleting and re-adding the entire code. This will help with better code review and collaboration.

**Comment by Tombstoner** [comment]
ok, I dont understand why that happened as the change was of only 2 lines. I will try again!

**Comment by Tombstoner** [comment]
are you able to review now ??

**Comment by Tombstoner** [comment]
thanks traveller08, your comment really made me review git commands again. My first legit open source contribution. Thanks again!

**Comment by Traveller08** [comment]
Thanks for your contribution @Tombstoner, you can browse other issues as well.
