### ISSUE TITLE
Design Suggestion for Blogs Page

### ISSUE THREAD

**Issue by Traveller08** [Traveller08/wecode#9]
**Description:**

We are looking for design suggestions to improve the appearance and user experience of the blogs page on our website.

**Design Suggestion:**
- Create a .doc or .pdf document outlining your design suggestion.
- Include details such as color schemes, layout, typography, and any visual elements you recommend.
- Provide a rationale for your design choices.

**Process for Making a Suggestion:**
1. Create a design suggestion document as per the provided template.
2. Upload the document to this issue.
3. Team members and contributors will review the suggestions.
4. If your suggestion is accepted, you can proceed to create a pull request (PR).

**Creating a Pull Request (PR):**
1. Fork this repository to your GitHub account.
2. Create a new branch for your design changes.
3. Implement the design changes based on the accepted suggestion.
4. Submit a pull request (PR) with your changes, referencing this issue.

**Blogs page:**

<img width="945" alt="Screenshot 2023-10-01 103645" src="https://github.com/Traveller08/wecode/assets/75868415/92d3eabb-fa01-4c97-a949-bf2bb413e95a">

**Comment by Prathamdas3** [comment]
Hi, I am interested in this issue, Do I need to change anything in the code or should I give the changes in a .pdf or .doc document?

**Comment by Traveller08** [comment]
Hi @Prathamdas3!
Yes, you need to change the styling of the page. Please attach a screenshot of the new design of the page along with your pull request.
